language: ruby
rvm: 2.4.0

before_script: chmod +x ./script/cibuild

before_install:
  - gem update --system
  - gem install bundler

script: ./script/cibuild

branches:
  only:
  - master      # test on master branch
  - /pages-(.*) # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache: bundler

sudo: false
