# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Eric T Leung
description:      'PhD student in bioinformatics and computational biology. Follow me on Twitter at <a href="https://twitter.com/erictleung">@erictleung</a>'
url:              http://erictleung.com

author:
  name:           'Eric Leung'
  url:            https://twitter.com/erictleung
  email:          leung@erictleung.com

paginate:         5

# Custom vars
version:          1.0.0
github:           https://github.com/erictleung

# Ruby plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Page List
pages_list:
  Blog: '/blog'
  Archive: '/archive'
  Feed: '/atom.xml'

# Default extension for new posts and pages
post_ext: md
page_ext: html
