# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:title

# Setup
title:            Eric Leung
description:      Eric Leung is a computational biology graduate student in the Department of Medical Informatics and Clinical Epidemiology at Oregon Health &amp; Science University
tagline:          PhD student in bioinformatics and computational biology. Follow me on Twitter at <a href="https://twitter.com/erictleung">@erictleung</a>
url:              https://erictleung.com

author:
  name:           'Eric Leung'
  url:            https://twitter.com/erictleung
  email:          leung@erictleung.com

paginate:         5
paginate_path:    "blog/page:num"

# Custom vars
version:          1.0.0
github:           https://github.com/erictleung

# Ruby plugins
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-seo-tag

# Page List
pages_list:
  About: '/about'
  Blog: '/blog'
  Archive: '/archive'
  Feed: '/atom.xml'

# Footer links
footer-links:
  github: erictleung
  twitter: erictleung

# Default extension for new posts and pages
post_ext: md
page_ext: html
