# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:title

# Setup
title:            Eric Leung
description:      Code, Data, Microbiome
sidebar: |
    Data scientist and consultant looking to connect people to
    data insights, automating boring work, and tearing down barriers to
    learning.<br/>Follow me on Twitter at
    <a href="https://twitter.com/erictleung">@erictleung</a>
url:              https://erictleung.com

# Author information
author:
  name:           'Eric T Leung'
  url:            https://twitter.com/erictleung
  email:          leung@erictleung.com

# Paging specification
paginate:         10
paginate_path:    "blog/page:num"

# Custom vars
version:          1.0.0
github:           https://github.com/erictleung

# Ruby plugins
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed

# Page List
pages_list:
  about: '/about'
  blog: '/blog'
  projects: '/projects'
  misc: '/misc'
  feed: '/feed.xml'

# Footer links
footer-links:
  github: erictleung
  twitter: erictleung
  linkedin: erictleung

# Social media information
twitter:
  username: erictleung
social:
  name: Eric Leung
  links:
    - https://twitter.com/erictleung
    - https://www.linkedin.com/in/erictleung
    - https://github.com/erictleung

# Default extension for new posts and pages
post_ext: md
page_ext: html
